#check updates in original helper scripts repo and make /dev update if needed
name: clone_and_create_dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC
  push:
    branches:
      - dev
jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
   
    - name: Set up Git and add upstream
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote add upstream https://github.com/community-scripts/ProxmoxVE.git
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name: Check if the dev branch exists, if not create it
      run: |
        # Check if the dev branch exists, if not create it
        git fetch samohosting-scripts
        branch_name=samohosting-scripts/dev
        if [ `git branch --list $branch_name` ]; then
          echo "Branch name $branch_name already exists."  
        else
          echo "Branch name $branch_name NOT FOUND."
        fi  
        # BRANCH_EXISTS=$(git show-ref refs/heads/dev)
        
        # if [ -z "$BRANCH_EXISTS" ]; then
        #   echo "dev branch does not exist"
        #   # Create a test file
        #   touch "test_dev_$(date '+%Y-%m-%d %H:%M:%S').txt"
          
        #   git add .
        #   git commit -m "test_dev_file_created_by_workflow: $(date +'%Y-%m-%d %H:%M:%S')"
        #   # Push the new branch
        #   git push -u samohosting-scripts dev
        #   echo "pushed test file in origin dev"
        # else
        #   echo "dev branch already exists, switching to dev branch"
        #   git switch dev
        # fi
