#check updates in original helper scripts repo and make /dev update if needed
name: clone_and_create_dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC
  push:
    branches:
      - dev
jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
   
    - name: Set up Git and add upstream
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote add upstream https://github.com/community-scripts/ProxmoxVE.git
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name: Check if the dev branch exists, create it if necessary (Verbose)
      run: |
        # Fetch branches from both repositories to ensure you're working with the latest data
        # git fetch upstream && echo "Fetched from upstream"
        git fetch samohosting-scripts && echo "Fetched from samohosting-scripts"

        # Check if dev branch exists in remote repository
        BRANCH_EXISTS=$(git ls-remote --heads samohosting-scripts refs/heads/dev)

        if [ -z "$BRANCH_EXISTS" ]; then
          echo "dev branch does not exist"
          
          # Create a test file and commit it
          touch "test_dev_$(date '+%Y-%m-%d %H:%M:%S').txt" && echo "Created test file"
          git add . && echo "Added files to staging area"
          git commit -m "test_dev_file_created_by_workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "Committed changes"
          
          # Push the new branch
          git push -u samohosting-scripts dev && echo "Pushed test file in origin dev"
        else
          echo "dev branch already exists, switching to dev branch"
          git switch dev && echo "Switched to dev branch"
        fi


    # - name: Check if the dev branch exists, if not create it
    #   run: |
    #     # Check if the dev branch exists, if not create it
    #     git fetch samohosting-scripts
    #     git show-ref refs/heads/dev
        
        # if [ -z "$branch_name" ]; then
        #   echo 'branch exists!'
        # else
        #   echo 'branch NOT exists!'
        # fi

        
        # if [ `git branch --list $branch_name` ]; then
        #   echo "Branch name $branch_name already exists."  
        # else
        #   echo "Branch name $branch_name NOT FOUND."
        # fi  
        # BRANCH_EXISTS=$(git show-ref refs/heads/dev)
        
        # if [ -z "$BRANCH_EXISTS" ]; then
        #   echo "dev branch does not exist"
        #   # Create a test file
        #   touch "test_dev_$(date '+%Y-%m-%d %H:%M:%S').txt"
          
        #   git add .
        #   git commit -m "test_dev_file_created_by_workflow: $(date +'%Y-%m-%d %H:%M:%S')"
        #   # Push the new branch
        #   git push -u samohosting-scripts dev
        #   echo "pushed test file in origin dev"
        # else
        #   echo "dev branch already exists, switching to dev branch"
        #   git switch dev
        # fi
