#check updates in original helper scripts repo and make /dev update if needed
name: clone_and_create_dev

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 2 * * *'  # Run every day at 2 AM UTC
  # push:
  #   branches:
  #     - dev
jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
   
    - name: Set up Git and add upstream
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote add upstream https://github.com/community-scripts/ProxmoxVE.git
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name: Check if the dev branch exists, create it if necessary
      run: |
        # Fetch branches from both repositories to ensure you're working with the latest data
        git fetch samohosting-scripts && echo "Fetched from samohosting-scripts $(date +'%Y-%m-%d %H:%M:%S')"

        # Check if dev branch exists in remote repository
        BRANCH_EXISTS=$(git ls-remote --heads samohosting-scripts refs/heads/dev)
        echo $BRANCH_EXISTS

        if [ -z "$BRANCH_EXISTS" ]; then
          #clone helper-scripts original repo
          git clone --single-branch --branch main https://github.com/community-scripts/ProxmoxVE.git
          cd ProxmoxVE
          git config user.name 'samohosting'
          git config user.email 'email@samohosting.ru'
          git add . && echo " DONE add ."
          git commit -m "pushing cloned repo to dev by workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "Committed changes"
          git push -u samohosting-scripts main:dev && echo "Pushed cloned repo file in samohosting-scripts/dev"
        else
          echo "exists!"
        fi

        #   git add . && echo "Added files to staging area(ready for push)"
        #   git commit -m "created_dev_branch_testfile_was_created_by_workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "Committed changes"

        #   # Push the new branch
        #   git push -u samohosting-scripts dev && echo "Pushed test file in origin dev"
        # else
        #   echo "dev branch already exists, switching to dev branch"
        #   git switch dev && echo "Has switched to dev branch"
        #   touch "existed_dev_branch_testfile_$(date '+%Y-%m-%d %H:%M:%S').txt" && echo "Created test file"
        #   git add . && echo "Added files to staging area(ready for push)"
        #   git commit -m "existed_dev_branch_testfile_was_created_by_workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "Committed changes"
        #   git push -u samohosting-scripts dev && echo "Pushed test file in existed origin dev"
        # fi
