#check updates in original helper scripts repo and make /community_repo_clone and update if needed
name: clone_and_create_community_repo_clone

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Run every day at 2 AM UTC
jobs:
  sync-repo:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
   
    - name: Set up Git and add upstream
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote add upstream https://github.com/community-scripts/ProxmoxVE.git
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name: Create\Update samohosting-scripts/community_repo_clone
      run: |
        # Fetch data from samohosting-scripts
        # git fetch samohosting-scripts && echo "info: Fetched from samohosting-scripts $(date +'%Y-%m-%d %H:%M:%S')"

        # Check if community_repo_clone branch exists in remote repository
        BRANCH_EXISTS=$(git ls-remote --heads samohosting-scripts refs/heads/community_repo_clone)
        if [ -z "$BRANCH_EXISTS" ]; then
          echo "info: cant find targeted community_repo_clone branch"
          
          #creating temp_local_community_repo_clone branch
          git checkout --orphan temp_local_community_repo_clone
          echo "CLEANING.." && git rm -rf . && echo "CLEANING DONE.."
          #clone helper-scripts original repo
          git show-branch --current
          git clone --single-branch --branch main https://github.com/community-scripts/ProxmoxVE.git temp_repo
          git show-branch --current
          cp -r temp_repo/* .
          rm -r temp_repo
          git add . && echo "info: DONE add . $(date +'%Y-%m-%d %H:%M:%S')"
          git commit -m "pushed ProxmoxVE cloned repo to community_repo_clone by workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "info: Committed changes $(date +'%Y-%m-%d %H:%M:%S')"
          git push -u samohosting-scripts temp_local_community_repo_clone:community_repo_clone && echo "info: Pushed cloned repo in samohosting-scripts/community_repo_clone $(date +'%Y-%m-%d %H:%M:%S')"
        else
          echo "info: found targeted branch -> $BRANCH_EXISTS"
          echo "info: Fetch the latest changes from both repositories $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Fetch the latest changes from both repositories
          git fetch samohosting-scripts community_repo_clone
          git fetch upstream main
          
          echo "info: checking diff samohosting-scripts/community_repo_clone VS community-scripts/ProxmoxVE $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Compare the main branches
          # if ! git diff --name-only samohosting-scripts/community_repo_clone..upstream/main -- . ':!.github' ':!.editorconfig'; then
          if  git diff samohosting-scripts/community_repo_clone..upstream/main; then
          echo "info: diff is detected in samohosting-scripts/community_repo_clone VS community-scripts/ProxmoxVE"
          echo "info: switching to samohosting-scripts/community_repo_clone"
          # Switch to the community_repo_clone branch and pull changes from upstream.
          git switch community_repo_clone && git pull
          echo "info: switched and pulled"
          echo "info: merging upstream/main" && git merge upstream/main --allow-unrelated-histories
          echo "info: sucsessfully merged"
          echo "info: deleting .github | .vscode | .editorconfig  ..."
          rm -rf .github && echo "info:  rm -rf .github"
          rm -rf .vscode && echo "info:  rm -rf .vscode"
          rm -rf .editorconfig && echo "info:  rm -rf .editorconfig"
          git add . && echo "info: DONE add . $(date +'%Y-%m-%d %H:%M:%S')"
          ls -a
          git commit -m "get_update_changes_from_helper-scripts_community $(date +'%Y-%m-%d %H:%M:%S')"
          echo "info: start pushing origin $(date +'%Y-%m-%d %H:%M:%S')"
          git push -u -f samohosting-scripts community_repo_clone:community_repo_clone 
          echo "info: Pushed repo update in samohosting-scripts/community_repo_clone $(date +'%Y-%m-%d %H:%M:%S')"
          else
          echo "info: No diff is detected in samohosting-scripts/community_repo_clone VS community-scripts/ProxmoxVE"
          fi
        fi
