name: update_dev_to_ru_dev

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev
  schedule:           
    - cron: '0 3 * * *'
    

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Setup name, email, and remote repository
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote remove samohosting-scripts || true
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name: Create or update ru_dev branch
      run: |
        # Fetch all branches
        git fetch samohosting-scripts

        # Ensure the dev branch exists locally
        if ! git show-ref --verify --quiet refs/remotes/samohosting-scripts/dev; then
          echo "error: Remote branch 'dev' does not exist. Aborting."
          exit 1
        fi

        # Check if ru_dev exists remotely
        if ! git show-ref --verify --quiet refs/remotes/samohosting-scripts/ru_dev; then
          echo "info: ru_dev branch does not exist. Creating it from dev..."
          git checkout -b ru_dev samohosting-scripts/dev
          git push samohosting-scripts ru_dev
        else
          echo "info: ru_dev branch exists. Checking out and updating..."
          git checkout ru_dev
          git pull samohosting-scripts ru_dev
        fi

        # Merge dev into ru_dev if there are changes
        git checkout ru_dev
        git fetch samohosting-scripts dev
        if ! git diff --quiet samohosting-scripts/dev; then
          echo "info: Changes detected in dev. Merging into ru_dev..."
          git merge samohosting-scripts/dev --allow-unrelated-histories -m "Merge updates from dev into ru_dev"
          git push samohosting-scripts ru_dev
        else
          echo "info: No changes detected. ru_dev is up to date."
        fi
