name: Merge main into update-app-headers

on:
  push:
    branches:
      - main
    paths:
      - 'ct/**.sh'

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge main into update-app-headers silently
        run: |
          git fetch origin
          git checkout update-app-headers
          git merge origin/main --allow-unrelated-histories --no-commit -m "Merge main into update-app-headers"
          git push origin update-app-headers > /dev/null 2>&1 || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
