#translation_en2ru and url update for all .sh
name: translation_en2ru

on:
  workflow_dispatch:
jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
   
    - name: Set up Git and add upstream
      run: |
        git config user.name 'samohosting'
        git config user.email 'email@samohosting.ru'
        git remote add samohosting-scripts https://github.com/samohosting-ru/samohosting-scripts.git

    - name:  translation_en2ru
      run: |
        git pull
        git show-branch
        git switch dev
        echo "dev looks now like that:" && ls
        git pull
        echo "after pull dev looks like that:" && ls
        git merge
        echo "after merge dev looks like that:" && ls
        find ./ -type f \( -name "*.sh" \) -exec sed -i "s|https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE|https://MY_LIINK/LICENS|g" {} +
        echo "LICENSE link was replaced"
        git add . && echo "info: DONE add . $(date +'%Y-%m-%d %H:%M:%S')"
        git commit -m "repo was translated en2ru by workflow: $(date +'%Y-%m-%d %H:%M:%S')" && echo "info: Committed changes $(date +'%Y-%m-%d %H:%M:%S')"
        git push -u samohosting-scripts dev:dev && echo "info: repo was translated en2ru by workflow $(date +'%Y-%m-%d %H:%M:%S')"
